#!/usr/bin/env python3
"""Merge semantic localization keys into Localizable.xcstrings."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
XCSTRINGS = ROOT / "CareMom2/Resources/Localizable.xcstrings"
WIDGET_XCSTRINGS = ROOT / "CareMomWidgets/Localizable.xcstrings"

# en -> ru pairs for semantic keys
TRANSLATIONS = {
    "onboarding.welcome": ("Welcome to CareMom", "Добро пожаловать в CareMom"),
    "onboarding.subtitle": (
        "Your child's health diary.\nAdd the first profile to get started.",
        "Дневник здоровья вашего ребёнка.\nДобавьте первый профиль, чтобы начать.",
    ),
    "onboarding.add_child": ("Add child", "Добавить ребёнка"),
    "onboarding.later": ("Later", "Позже"),
    "settings.import.success": ("Imported profiles: %lld", "Импортировано профилей: %lld"),
    "settings.import.error": ("Import error: %@", "Ошибка импорта: %@"),
    "settings.language.ru": ("Russian", "Русский"),
    "settings.language.en": ("English", "English"),
    "empty.add_child_title": ("Add a child", "Добавьте ребёнка"),
    "empty.add_child_hint": (
        "Create a profile to start tracking health",
        "Создайте профиль, чтобы начать вести дневник здоровья",
    ),
    "empty.no_entries_title": ("No entries yet", "Пока нет записей"),
    "empty.no_entries_hint": (
        "Tap + or 🌡 for a quick entry",
        "Нажмите + или 🌡 для быстрой записи",
    ),
    "empty.no_profiles_title": ("No profiles", "Нет профилей"),
    "empty.add_profile_hint": ("Add a child profile", "Добавьте профиль ребёнка"),
    "children.title": ("Children", "Дети"),
    "child.medical_info": ("Medical information", "Медицинская информация"),
    "child.gender": ("Gender", "Пол"),
    "child.blood_type": ("Blood type", "Группа крови"),
    "child.allergies": ("Allergies", "Аллергии"),
    "child.chronic": ("Chronic conditions", "Хронические"),
    "child.chronic_conditions": ("Chronic conditions", "Хронические заболевания"),
    "child.none": ("None", "Нет"),
    "child.stats": ("Statistics", "Статистика"),
    "child.diary_entries": ("Diary entries", "Записей в дневнике"),
    "child.medication_courses": ("Medication courses", "Курсов лекарств"),
    "child.growth_measurements": ("Growth measurements", "Измерений роста"),
    "child.vaccinations_count": ("Vaccinations", "Прививок"),
    "child.pdf_export": ("PDF export", "Экспорт PDF"),
    "child.period": ("Period", "Период"),
    "child.export_pdf": ("Export to PDF", "Экспорт в PDF"),
    "child.export_doctor_pdf": ("Doctor PDF (14 days)", "PDF для врача (14 дней)"),
    "child.edit": ("Edit", "Изменить"),
    "child.growth_section": ("Growth & weight", "Рост и вес"),
    "child.weight": ("Weight", "Вес"),
    "child.height": ("Height", "Рост"),
    "child.date": ("Date", "Дата"),
    "child.no_measurements": ("No measurements yet", "Пока нет измерений"),
    "child.add_measurement": ("Add measurement", "Добавить измерение"),
    "child.new_measurement": ("New measurement", "Новое измерение"),
    "child.basic": ("Basic", "Основное"),
    "child.first_name": ("First name", "Имя"),
    "child.last_name": ("Last name", "Фамилия"),
    "child.date_of_birth": ("Date of birth", "Дата рождения"),
    "child.health": ("Health", "Здоровье"),
    "child.new_profile": ("New profile", "Новый профиль"),
    "child.edit_profile": ("Edit profile", "Редактировать"),
    "stats.title": ("Statistics", "Статистика"),
    "stats.period": ("Period", "Период"),
    "stats.illness_this_month": ("Sick this month", "Болел в этом месяце"),
    "stats.illness_this_year": ("Sick this year", "Болел в этом году"),
    "stats.medications_taken": ("Medications taken", "Лекарств принято"),
    "stats.total_entries": ("Total entries", "Всего записей"),
    "stats.temperature_chart": ("Temperature chart", "График температуры"),
    "stats.symptoms_chart": ("Symptom frequency", "Частота симптомов"),
    "stats.top_medications": ("Common medications", "Частые лекарства"),
    "stats.illness_calendar": ("Illness calendar", "Календарь болезней"),
    "stats.period.week": ("Week", "Неделя"),
    "stats.period.month": ("Month", "Месяц"),
    "stats.period.year": ("Year", "Год"),
    "stats.period.all": ("All", "Всё"),
    "chart.date": ("Date", "Дата"),
    "chart.count": ("Count", "Кол-во"),
    "chart.symptom": ("Symptom", "Симптом"),
    "chart.value": ("Value", "Значение"),
    "meds.title": ("Medications", "Лекарства"),
    "meds.no_active": ("No active courses", "Нет активных курсов"),
    "meds.no_active_hint": (
        "Create a medication course with reminders",
        "Создайте курс лекарства с напоминаниями",
    ),
    "meds.days_short": ("%lld d.", "%lld дн."),
    "meds.times_per_day": ("%lld× per day", "%lld× в день"),
    "meds.course_progress": ("Course progress", "Прогресс курса"),
    "meds.taken": ("Taken", "Принято"),
    "meds.skip": ("Skip", "Пропустить"),
    "meds.medication": ("Medication", "Лекарство"),
    "meds.name": ("Name", "Название"),
    "meds.dosage": ("Dosage", "Дозировка"),
    "meds.course": ("Course", "Курс"),
    "meds.days_stepper": ("Days: %lld", "Дней: %lld"),
    "meds.doses_stepper": ("Doses per day: %lld", "Приёмов в день: %lld"),
    "meds.first_reminder": ("First reminder", "Первое напоминание"),
    "meds.push_reminders": ("Push reminders", "Push-напоминания"),
    "meds.new_course": ("New course", "Новый курс"),
    "meds.create": ("Create", "Создать"),
    "meds.disable_reminders": ("Turn off reminders", "Отключить напоминания"),
    "meds.enable_reminders": ("Turn on reminders", "Включить напоминания"),
    "meds.delete_course": ("Delete course", "Удалить курс"),
    "meds.delete_course_confirm": ("Delete this medication course?", "Удалить этот курс лекарства?"),
    "meds.delete_course_message": (
        "All scheduled push reminders for this course will be cancelled.",
        "Все запланированные push-напоминания по этому курсу будут отменены.",
    ),
    "meds.reminders_on": ("Reminders on", "Напоминания включены"),
    "meds.reminders_off": ("Reminders off", "Напоминания выключены"),
    "vac.title": ("Vaccinations", "Прививки"),
    "vac.recommended": ("Recommended schedule", "Рекомендуемый календарь"),
    "vac.add": ("Add", "Добавить"),
    "vac.empty": ("No vaccinations", "Нет прививок"),
    "vac.my_vaccinations": ("My vaccinations", "Мои прививки"),
    "vac.done": ("Done", "Сделано"),
    "vac.vaccine": ("Vaccine", "Прививка"),
    "vac.choose": ("Choose", "Выберите"),
    "vac.custom_name": ("Or custom name", "Или своё название"),
    "vac.notes": ("Notes", "Заметки"),
    "vac.new": ("New vaccination", "Новая прививка"),
    "growth.title": ("Growth & weight", "Рост и вес"),
    "growth.add_profile_first": (
        "Add a child profile first",
        "Сначала добавьте профиль ребёнка",
    ),
    "growth.no_measurements": ("No measurements", "Нет измерений"),
    "growth.track_hint": (
        "Record weight and height to track progress",
        "Запишите вес и рост ребёнка, чтобы отслеживать динамику",
    ),
    "growth.weight_kg": ("Weight (kg)", "Вес (кг)"),
    "growth.height_cm": ("Height (cm)", "Рост (см)"),
    "growth.history": ("History", "История"),
    "growth.unit.kg": ("kg", "кг"),
    "growth.unit.cm": ("cm", "см"),
    "growth.weight_format": ("%.2f kg", "%.2f кг"),
    "growth.height_format": ("%.0f cm", "%.0f см"),
    "growth.measurement": ("Measurement", "Измерение"),
    "growth.previous": ("Previous", "Предыдущее"),
    "growth.comment": ("Comment", "Комментарий"),
    "entry.edit": ("Edit entry", "Редактировать"),
    "entry.new": ("New entry", "Новая запись"),
    "entry.date_time": ("Date & time", "Дата и время"),
    "entry.templates": ("Templates", "Шаблоны"),
    "entry.photo": ("Photo", "Фото"),
    "entry.add_photo": ("Add photo", "Добавить фото"),
    "entry.photo_added": ("Photo added", "Фото добавлено"),
    "entry.type_section": ("Entry type", "Тип записи"),
    "entry.title_field": ("Title", "Заголовок"),
    "entry.temperature": ("Temperature", "Температура"),
    "entry.symptoms": ("Symptoms", "Симптомы"),
    "entry.medication_name": ("Medication name", "Название лекарства"),
    "entry.notes": ("Notes", "Заметки"),
    "entry.notes_placeholder": ("Additional details...", "Дополнительные детали..."),
    "entry.delete_confirm": ("Delete entry?", "Удалить запись?"),
    "entry.delete_message": (
        "This entry cannot be restored.",
        "Эту запись нельзя будет восстановить.",
    ),
    "entry.detail.medication": ("Medication", "Лекарство"),
    "common.add": ("Add", "Добавить"),
    "common.edit": ("Edit", "Изменить"),
    "common.delete": ("Delete", "Удалить"),
    "common.notes": ("Notes", "Заметки"),
    "common.ok": ("OK", "OK"),
    "accessibility.add_entry": ("Add entry", "Добавить запись"),
    "lock.verify_identity": ("Verify your identity", "Подтвердите личность"),
    "lock.unlock": ("Unlock", "Разблокировать"),
    "lock.reason": (
        "Unlock CareMom to access your child's data",
        "Разблокируйте CareMom для доступа к данным ребёнка",
    ),
    "voice.title": ("Voice note", "Голосовая заметка"),
    "voice.stop": ("Stop", "Стоп"),
    "voice.record": ("Record", "Запись"),
    "voice.delete_recording": ("Delete recording", "Удалить запись"),
    "voice.start": ("Start recording", "Начать запись"),
    "voice.no_mic": ("No microphone access", "Нет доступа к микрофону"),
    "voice.no_mic_message": (
        "Allow microphone access in iPhone Settings to record voice notes.",
        "Разрешите доступ к микрофону в Настройках iPhone, чтобы записывать голосовые заметки.",
    ),
    "voice.recording": ("Recording... %@", "Запись... %@"),
    "voice.playing": ("Playing...", "Воспроизведение..."),
    "voice.tap_play": ("Tap ▶ to listen", "Нажмите ▶ чтобы прослушать"),
    "voice.hint": ("Record a voice note", "Запишите голосовую заметку"),
    "age.newborn": ("newborn", "новорождённый"),
    "blood.unknown": ("Unknown", "Не знаю"),
    "template.temperature": ("Temperature", "Температура"),
    "template.nurofen": ("Nurofen", "Нурофен"),
    "template.nurofen_note": ("Fever reducer", "Жаропонижающее"),
    "template.cough": ("Cough", "Кашель"),
    "template.pediatrician": ("Pediatrician", "Педиатр"),
    "template.pediatrician_visit": ("Pediatrician visit", "Приём педиатра"),
    "template.doctor_questions": ("Questions for doctor", "Вопросы врачу"),
    "template.poor_sleep": ("Poor sleep", "Плохой сон"),
    "template.restless_sleep": ("Restless sleep", "Беспокойный сон"),
    "template.rash": ("Rash", "Сыпь"),
    "template.doctor_checklist": (
        "□ Temperature and symptoms in recent days\n□ Allergies and medication tolerance\n□ Appetite, sleep, activity\n□ Rash, cough, runny nose — when it started\n□ Medications given and whether they helped\n□ Tests / referrals needed",
        "□ Температура и симптомы за последние дни\n□ Аллергии и переносимость лекарств\n□ Аппетит, сон, активность\n□ Сыпь, кашель, насморк — когда началось\n□ Какие лекарства давали и помогло ли\n□ Нужны ли анализы / направления",
    ),
    "vaccine.bcg": ("BCG", "БЦЖ"),
    "vaccine.hepatitis_b": ("Hepatitis B", "Гепатит B"),
    "vaccine.dtp": ("DTP", "АКДС"),
    "vaccine.polio": ("Polio", "Полиомиелит"),
    "vaccine.mmr": ("MMR", "КПК"),
    "vaccine.flu": ("Flu", "Грипп"),
    "schedule.hep_b_1": ("Hepatitis B (1)", "Гепатит B (1)"),
    "schedule.bcg": ("BCG", "БЦЖ"),
    "schedule.dtp_1": ("DTP (1)", "АКДС (1)"),
    "schedule.polio_1": ("Polio (1)", "Полиомиелит (1)"),
    "schedule.hep_b_2": ("Hepatitis B (2)", "Гепатит B (2)"),
    "schedule.dtp_2": ("DTP (2)", "АКДС (2)"),
    "schedule.polio_2": ("Polio (2)", "Полиомиелит (2)"),
    "schedule.dtp_3": ("DTP (3)", "АКДС (3)"),
    "schedule.polio_3": ("Polio (3)", "Полиомиелит (3)"),
    "schedule.hep_b_3_4m": ("Hepatitis B (3)", "Гепатит B (3)"),
    "schedule.hep_b_3_6m": ("Hepatitis B (3)", "Гепатит B (3)"),
    "schedule.mmr_1": ("MMR (1)", "КПК (1)"),
    "schedule.mmr_2": ("MMR (2)", "КПК (2)"),
    "schedule.dtp_revacc_18m": ("DTP (booster)", "АКДС (ревакц.)"),
    "schedule.polio_revacc_18m": ("Polio (booster)", "Полиомиелит (ревакц.)"),
    "schedule.dtp_revacc_6y": ("DTP (booster)", "АКДС (ревакц.)"),
    "schedule.age.0m": ("0 mo", "0 мес"),
    "schedule.age.0_1m": ("0–1 mo", "0–1 мес"),
    "schedule.age.1m": ("1 mo", "1 мес"),
    "schedule.age.2m": ("2 mo", "2 мес"),
    "schedule.age.3m": ("3 mo", "3 мес"),
    "schedule.age.4m": ("4 mo", "4 мес"),
    "schedule.age.6m": ("6 mo", "6 мес"),
    "schedule.age.12m": ("12 mo", "12 мес"),
    "schedule.age.18m": ("18 mo", "18 мес"),
    "schedule.age.6y": ("6 years", "6 лет"),
    "notification.medication.title": ("Time to take medication", "Время принять лекарство"),
    "notification.vaccination.title": ("Vaccination reminder", "Напоминание о прививке"),
    "notification.vaccination.body": ("%@: %@ — in 3 days", "%@: %@ — через 3 дня"),
    "siri.recorded_note": ("Recorded via Siri", "Записано через Siri"),
    "intent.temperature.short": ("Temperature", "Температура"),
    "intent.diary.short": ("Diary", "Дневник"),
    "intent.record_temperature": ("Record temperature", "Записать температуру"),
    "intent.record_temperature.description": ("Quick temperature entry for your child", "Быстрая запись температуры ребёнка"),
    "intent.record_temperature.dialog": ("Open CareMom — %@° will be recorded", "Откройте CareMom — температура %@° будет записана"),
    "intent.open_diary": ("Open diary", "Открыть дневник"),
    "pdf.subject_since": ("Since %@", "С %@"),
    "pdf.health_diary": ("Health diary — %@", "Дневник здоровья — %@"),
    "pdf.dob_age": ("Date of birth: %@ · %@", "Дата рождения: %@ · %@"),
    "pdf.entries_since": ("Entries since %@", "Записи с %@"),
    "pdf.temperature": ("Temperature: %.1f°C", "Температура: %.1f°C"),
    "pdf.doctor_report": ("Doctor report — %@", "Справка для врача — %@"),
    "pdf.blood_allergies": ("Blood type: %@ · Allergies: %@", "Группа крови: %@ · Аллергии: %@"),
    "pdf.chronic": ("Chronic: %@", "Хронические: %@"),
    "pdf.temperature_14d": ("Temperature (14 days):", "Температура (14 дней):"),
    "pdf.symptoms_illnesses": ("Symptoms & illnesses:", "Симптомы и болезни:"),
    "pdf.medications": ("Medications:", "Лекарства:"),
    "pdf.generated": ("Generated by CareMom · %@", "Сформировано CareMom · %@"),
    "pdf.export.failed": ("Could not create PDF. Please try again.", "Не удалось создать PDF. Попробуйте ещё раз."),
    "settings.backup.hint": (
        "Backup includes diary entries, growth, vaccinations, and medication courses. Photos and voice notes are not included.",
        "Резервная копия включает записи дневника, рост, прививки и курсы лекарств. Фото и голосовые заметки не сохраняются.",
    ),
    "settings.export.failed": ("Export failed: %@", "Ошибка экспорта: %@"),
    "settings.privacy_policy": ("Privacy Policy", "Политика конфиденциальности"),
    "privacy.title": ("Privacy Policy", "Политика конфиденциальности"),
    "privacy.data_title": ("Data we store", "Какие данные хранятся"),
    "privacy.data_body": (
        "Child profiles, diary entries (symptoms, medications, photos, voice notes), growth and vaccination records.",
        "Профили детей, записи дневника (симптомы, лекарства, фото, голосовые заметки), рост и прививки.",
    ),
    "privacy.storage_title": ("Where data is stored", "Где хранятся данные"),
    "privacy.storage_body": (
        "On your device only. We do not sell data or use third-party analytics.",
        "Только на вашем устройстве. Мы не продаём данные и не используем стороннюю аналитику.",
    ),
    "privacy.permissions_title": ("Permissions", "Разрешения"),
    "privacy.permissions_body": (
        "Notifications (medication reminders), photos, microphone, Face ID, and speech recognition are used only for features you enable.",
        "Уведомления (лекарства), фото, микрофон, Face ID и распознавание речи — только для функций, которые вы включаете.",
    ),
    "privacy.backup_title": ("Backup", "Резервная копия"),
    "privacy.backup_body": (
        "JSON export is created on device and shared only where you choose.",
        "Экспорт JSON создаётся на устройстве и передаётся только туда, куда вы сами отправите файл.",
    ),
    "privacy.tracking_title": ("Tracking", "Отслеживание"),
    "privacy.tracking_body": (
        "No ads. No cross-app tracking.",
        "Нет рекламы. Нет отслеживания между приложениями.",
    ),
    "privacy.contact": (
        "Questions: kemal.z.a@icloud.com",
        "Вопросы: kemal.z.a@icloud.com",
    ),
    "settings.icloud.paid_hint": (
        "iCloud sync requires CloudKit setup in a paid Apple Developer account. Use “Share data with family” for a JSON backup instead.",
        "iCloud требует платный Apple Developer и настройку CloudKit. Пока используйте «Поделиться данными с семьёй» — JSON-резервная копия.",
    ),
    "widget.no_temperature": ("No temperature", "Нет температуры"),
    "widget.add_child": ("Add a child", "Добавьте ребёнка"),
    "widget.open_add_profile": ("Open CareMom and add a child profile", "Откройте CareMom и добавьте профиль ребёнка"),
    "widget.temperature": ("Temperature", "Температура"),
    "widget.sick": ("Sick days", "Болел"),
    "widget.medication": ("Medication", "Лекарство"),
    "widget.no_reminders": ("No reminders", "Нет напоминаний"),
    "widget.health_diary": ("Health diary", "Дневник здоровья"),
    "widget.health_diary.description": ("Temperature, illnesses and medications.", "Температура, болезни и лекарства ребёнка."),
    "widget.next_medication": ("Next medication", "Следующее лекарство"),
    "widget.next_medication.description": ("Upcoming medication dose.", "Ближайший приём лекарства."),
}

WIDGET_KEYS = {k: v for k, v in TRANSLATIONS.items() if k.startswith("widget.")}


def make_entry(en: str, ru: str) -> dict:
    return {
        "localizations": {
            "en": {"stringUnit": {"state": "translated", "value": en}},
            "ru": {"stringUnit": {"state": "translated", "value": ru}},
        }
    }


def main() -> None:
    data = json.loads(XCSTRINGS.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    for key, (en, ru) in TRANSLATIONS.items():
        strings[key] = make_entry(en, ru)
    data["sourceLanguage"] = "en"
    XCSTRINGS.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Merged {len(TRANSLATIONS)} keys into {XCSTRINGS}")

    widget_data = {"sourceLanguage": "en", "strings": {}, "version": "1.0"}
    for key, (en, ru) in WIDGET_KEYS.items():
        widget_data["strings"][key] = make_entry(en, ru)
    WIDGET_XCSTRINGS.write_text(json.dumps(widget_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(WIDGET_KEYS)} widget keys into {WIDGET_XCSTRINGS}")


if __name__ == "__main__":
    main()
